# 0-add_integer.txt
===================
The 0-add_integer.py module
===================

Import function from the module:
    >>> add_integer = __import__("0-add_integer").add_integer


::

    >>> x = __import__("0-add_integer">).__doc__
    >>> len(x) > 1
    True
::

    >>> y = __import__("0-add_integer").add_integer.__doc__
    >>> len(y) > 1
    True

Function works with addition:

    >>> add_integer(2, 3)
    5


Function check negative with positive:
	 >>> add_integer(-6, 8)
	 2

Function check positive with negative:
    >>> add_integer(2, -4)
    -2

Addition over multiple values:
    >>> [add_integer(i, i ** 2) for i in range(6)]
    [0, 2, 6, 12, 20, 30]

Float and non-float values can be combined:
    >>> add_integer(2.1, 4)
    6

::
    >>> add_integer(5, 7.8)
    12

::
    >>> add_integer(2.45, 3.1)
    12

Validating for passed NaN:
	 >>> add_integer(1, float('nan'))
	 Traceback (most recent call last):
	 ValueError: cannot convert float NaN to integer

Validating for passed inf:
	 >>> add_integer(1, float('inf'))
	 Traceback (most recent call last):
	 OverflowError: cannot convert float infinity to integer

Validating super long int:
	 >>> add_integer(999999999999999999999999999999, 1)
	 1000000000000000000000000000000

Validating non-number with number:
	 >>> add_integer([1], 2)
	 Traceback (most recent call last):
	 TypeError: a must be an integer

Validating number with non-number:
	 >>> add_integer(3, "2")
	 Traceback (most recent call last):

	 TypeError: b must be an integer

Validating non-number with non-number:
	 >>> add_integer((2,), {"key": "value"})
         Traceback (most recent call last):
         TypeError: a must be an integer

Validating bool with number:
	 >>> add_integer(True, 1)
	 Traceback (most recent call last):
         TypeError: a must be an integer

Validating number with bool:
	 >>> add_integer(0, False)
         Traceback (most recent call last):
         TypeError: b must be an integer

Validating no args:
	 >>> add_integer()
	 Traceback (most recent call last):
	 TypeError: add_integer() missing 2 required positional arguments: 'a' and 'b'

Validating one arg:
	 >>> add_integer(1)
	 Traceback (most recent call last):
	 TypeError: add_integer() missing 1 required positional argument: 'b'

Validating more than 2 args:
	 >>> add_integer(1, 2, 3)
         Traceback (most recent call last):
         TypeError: add_integer() takes 2 positional arguments but 3 were given

